//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Cuahangxe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class XEGANMAY
    {
        
        public XEGANMAY()
        {
            this.CHITIETDONTHANGs = new HashSet<CHITIETDONTHANG>();
            this.SANXUATXEs = new HashSet<SANXUATXE>();
        }
    
        public int MaXe { get; set; }
        public string TenXe { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        [AllowHtml]
        public string Mota { get; set; }
        public string Anhbia { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public Nullable<int> MaLX { get; set; }
        public Nullable<int> MaNPP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONTHANG> CHITIETDONTHANGs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANXUATXE> SANXUATXEs { get; set; }
    }
}
